package com.chubb.apac.claims.modulith.config.config;
import com.chubb.apac.claims.modulith.common.enums.*;import com.chubb.apac.claims.modulith.config.model.*;import com.chubb.apac.claims.modulith.config.repository.*;import java.math.BigDecimal;import java.util.Map;import org.springframework.boot.CommandLineRunner;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.context.annotation.*;
@Configuration
public class InitialConfigurationData {
 @Bean @ConditionalOnProperty(name="cmx.configuration.seed-enabled",havingValue="true",matchIfMissing=true)
 CommandLineRunner seedConfiguration(MarketConfigurationRepository markets,ProductConfigurationRepository products,SlaConfigurationRepository slas,BusinessRuleRepository rules){return args->{
  Map<Market,String[]> metadata=Map.of(Market.SG,new String[]{"Singapore","SGD","en","Asia/Singapore"},Market.MY,new String[]{"Malaysia","MYR","en","Asia/Kuala_Lumpur"},Market.TH,new String[]{"Thailand","THB","th","Asia/Bangkok"},Market.ID,new String[]{"Indonesia","IDR","id","Asia/Jakarta"},Market.PH,new String[]{"Philippines","PHP","en","Asia/Manila"},Market.VN,new String[]{"Vietnam","VND","vi","Asia/Ho_Chi_Minh"});
  for(var entry:metadata.entrySet()){Market market=entry.getKey();String[] m=entry.getValue();if(!markets.existsByMarket(market)){MarketConfiguration x=new MarketConfiguration();x.setMarket(market);x.setName(m[0]);x.setCurrency(m[1]);x.setLanguage(m[2]);x.setTimezone(m[3]);x.setCreatedBy("seed");x.setUpdatedBy("seed");markets.save(x);}for(ProductType type:ProductType.values()){if(!products.existsByMarketAndProductType(market,type)){ProductConfiguration p=new ProductConfiguration();p.setMarket(market);p.setProductType(type);p.setClaimLimitMin(BigDecimal.ZERO);p.setClaimLimitMax(new BigDecimal("1000000.00"));p.setCreatedBy("seed");p.setUpdatedBy("seed");products.save(p);}if(!slas.existsByMarketAndProductType(market,type)){SlaConfiguration s=new SlaConfiguration();s.setMarket(market);s.setProductType(type);s.setAssessmentSlaDays(5);s.setDecisionSlaDays(2);s.setCreatedBy("seed");s.setUpdatedBy("seed");slas.save(s);}seedRule(rules,market,type,"MAX_CLAIM_AMOUNT","1000000.00","Maximum permitted claim amount");seedRule(rules,market,type,"REQUIRE_FINDINGS","true","Assessment findings are mandatory");}}
 };}
 private static void seedRule(BusinessRuleRepository rules,Market market,ProductType type,String key,String value,String description){if(!rules.existsByMarketAndProductTypeAndRuleKey(market,type,key)){BusinessRule r=new BusinessRule();r.setMarket(market);r.setProductType(type);r.setRuleKey(key);r.setRuleValue(value);r.setDescription(description);r.setCreatedBy("seed");r.setUpdatedBy("seed");rules.save(r);}}
}
