package com.chubb.apac.claims.modulith.claim.service.impl;
import com.chubb.apac.claims.modulith.claim.dto.response.*;import com.chubb.apac.claims.modulith.claim.event.*;import com.chubb.apac.claims.modulith.claim.mapper.ClaimMapper;import com.chubb.apac.claims.modulith.claim.model.*;import com.chubb.apac.claims.modulith.claim.repository.*;import com.chubb.apac.claims.modulith.claim.service.ClaimService;import com.chubb.apac.claims.modulith.common.dto.PageResponse;import com.chubb.apac.claims.modulith.common.enums.*;import com.chubb.apac.claims.modulith.common.exception.*;import java.time.Instant;import java.util.*;import org.springframework.context.ApplicationEventPublisher;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class ClaimServiceImpl implements ClaimService {
 private final ClaimRepository claims;private final ClaimStatusHistoryRepository history;private final ClaimAssignmentRepository assignments;private final ClaimMapper mapper;private final ApplicationEventPublisher events;
 public ClaimServiceImpl(ClaimRepository claims,ClaimStatusHistoryRepository history,ClaimAssignmentRepository assignments,ClaimMapper mapper,ApplicationEventPublisher events){this.claims=claims;this.history=history;this.assignments=assignments;this.mapper=mapper;this.events=events;}
 @Transactional(readOnly=true) public PageResponse<ClaimResponse> listForClaimant(String id,ClaimStatus status,Pageable p){Page<Claim> page=status==null?claims.findByClaimantId(id,p):claims.findByClaimantIdAndStatus(id,status,p);return PageResponse.from(page.map(mapper::toResponse));}
 @Transactional(readOnly=true) public ClaimDetailResponse getForClaimant(String id,String claimId){Claim c=claims.findByClaimIdAndClaimantId(claimId,id).orElseThrow(()->new ResourceNotFoundException("Claim not found"));return detail(c);}
 @Transactional(readOnly=true) public ClaimStatusResponse getStatusForClaimant(String id,String claimId){Claim c=claims.findByClaimIdAndClaimantId(claimId,id).orElseThrow(()->new ResourceNotFoundException("Claim not found"));return new ClaimStatusResponse(c.getClaimId(),c.getStatus(),c.getUpdatedAt());}
 @Transactional(readOnly=true) public PageResponse<ClaimResponse> listForStaff(Set<Market> allowed,ClaimStatus status,Market market,ProductType product,String assignedTo,Pageable p){ensureMarkets(allowed);if(market!=null&&!allowed.contains(market))throw new ForbiddenException("Market access is denied");Specification<Claim> spec=Specification.where(ClaimSpecifications.visibleTo(allowed)).and(ClaimSpecifications.hasStatus(status)).and(ClaimSpecifications.hasMarket(market)).and(ClaimSpecifications.hasProduct(product)).and(ClaimSpecifications.assignedTo(assignedTo));return PageResponse.from(claims.findAll(spec,p).map(mapper::toResponse));}
 @Transactional(readOnly=true) public ClaimDetailResponse getForStaff(Set<Market> allowed,String claimId){ensureMarkets(allowed);return detail(claims.findByClaimIdAndMarketIn(claimId,allowed).orElseThrow(()->new ResourceNotFoundException("Claim not found")));}
 public ClaimAssignmentResponse assignToSelf(Set<Market> allowed,String staffId,String claimId,String correlationId){ensureMarkets(allowed);Claim c=claims.findForUpdate(claimId,allowed).orElseThrow(()->new ResourceNotFoundException("Claim not found"));if(c.getAssignedStaffId()!=null){if(c.getAssignedStaffId().equals(staffId))throw new ConflictException("Claim is already assigned to current user");throw new ConflictException("Claim is already assigned to another staff member");}if(c.getStatus()!=ClaimStatus.REPORTED)throw new ConflictException("Only a reported claim can be assigned");Instant now=Instant.now();c.setAssignedStaffId(staffId);changeStatus(c,ClaimStatus.UNDER_REVIEW,"Claim assigned to staff",staffId,correlationId);ClaimAssignment a=new ClaimAssignment();a.setClaimId(claimId);a.setStaffId(staffId);a.setAssignedAt(now);a.setCreatedBy(staffId);a.setUpdatedBy(staffId);assignments.save(a);events.publishEvent(new ClaimAssignedEvent(UUID.randomUUID().toString(),claimId,staffId,c.getMarket(),now,correlation(correlationId)));return new ClaimAssignmentResponse(claimId,staffId,null,now);}
 public ClaimUnassignmentResponse unassignFromSelf(Set<Market> allowed,String staffId,String claimId,String correlationId){ensureMarkets(allowed);Claim c=claims.findForUpdate(claimId,allowed).orElseThrow(()->new ResourceNotFoundException("Claim not found"));if(c.getAssignedStaffId()==null)throw new ConflictException("Claim is not assigned");if(!c.getAssignedStaffId().equals(staffId))throw new ForbiddenException("Only the assigned staff member can unassign this claim");Instant now=Instant.now();c.setAssignedStaffId(null);changeStatus(c,ClaimStatus.REPORTED,"Claim unassigned by staff",staffId,correlationId);ClaimAssignment a=assignments.findFirstByClaimIdAndUnassignedAtIsNullOrderByAssignedAtDesc(claimId).orElseThrow(()->new IllegalStateException("Active claim assignment was not found"));a.setUnassignedAt(now);a.setUpdatedBy(staffId);return new ClaimUnassignmentResponse(claimId,now);}
 private ClaimDetailResponse detail(Claim c){return mapper.toDetail(c,history.findByClaimIdOrderByChangedAtAsc(c.getClaimId()));}
 private void changeStatus(Claim c,ClaimStatus next,String reason,String actor,String correlationId){ClaimStatus old=c.getStatus();c.setStatus(next);c.setUpdatedBy(actor);ClaimStatusHistory h=new ClaimStatusHistory();h.setClaimId(c.getClaimId());h.setOldStatus(old);h.setNewStatus(next);h.setReason(reason);h.setChangedBy(actor);h.setChangedAt(Instant.now());h.setCreatedBy(actor);h.setUpdatedBy(actor);history.save(h);events.publishEvent(new ClaimStatusChangedEvent(UUID.randomUUID().toString(),c.getClaimId(),old,next,reason,actor,Instant.now(),correlation(correlationId)));}
 private void ensureMarkets(Set<Market> markets){if(markets==null||markets.isEmpty())throw new ForbiddenException("No market access is assigned");}
 private String correlation(String v){return v==null||v.isBlank()?UUID.randomUUID().toString():v;}
}
