package com.chubb.apac.claims.modulith.inforequest.service;
import com.chubb.apac.claims.modulith.claim.api.ClaimModuleApi;import com.chubb.apac.claims.modulith.common.enums.Market;import com.chubb.apac.claims.modulith.common.exception.ConflictException;import com.chubb.apac.claims.modulith.inforequest.dto.request.*;import com.chubb.apac.claims.modulith.inforequest.event.*;import com.chubb.apac.claims.modulith.inforequest.mapper.InformationRequestMapper;import com.chubb.apac.claims.modulith.inforequest.model.*;import com.chubb.apac.claims.modulith.inforequest.repository.*;import com.chubb.apac.claims.modulith.inforequest.service.impl.InformationRequestServiceImpl;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.context.ApplicationEventPublisher;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class InformationRequestServiceImplTest {
 @Mock InformationRequestRepository requests;@Mock InformationResponseRepository responses;@Mock ClaimModuleApi claims;@Mock InformationRequestIdGenerator ids;@Mock ApplicationEventPublisher events;InformationRequestServiceImpl service;
 @BeforeEach void setup(){service=new InformationRequestServiceImpl(requests,responses,claims,new InformationRequestMapper(),ids,events);}
 @Test void staffCreatesRequest(){when(ids.nextRequestId()).thenReturn("IRQ-1");when(requests.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));var out=service.create("CLM-1","S1",Set.of(Market.SG),"C1",new CreateInformationRequest(List.of("Police Report","Police Report"),LocalDate.now(),"Upload"));assertThat(out.requestedFields()).containsExactly("Police Report");verify(events).publishEvent(any(InformationRequestedEvent.class));}
 @Test void rejectsSecondActiveRequest(){when(requests.existsByClaimIdAndStatusIn(eq("CLM-1"),any())).thenReturn(true);assertThatThrownBy(()->service.create("CLM-1","S1",Set.of(Market.SG),"C1",new CreateInformationRequest(List.of("Invoice"),LocalDate.now(),null))).isInstanceOf(ConflictException.class);}
 @Test void claimantSubmitsResponse(){InformationRequest q=new InformationRequest();q.setRequestId("IRQ-1");q.setClaimId("CLM-1");q.setStatus(InformationRequestStatus.PENDING);when(requests.findForUpdate("IRQ-1","CLM-1")).thenReturn(Optional.of(q));when(ids.nextResponseId()).thenReturn("IRS-1");when(responses.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));var out=service.submit("CLM-1","IRQ-1","U1","C1",new SubmitInformationResponse("Attached details"));assertThat(out.responseId()).isEqualTo("IRS-1");assertThat(q.getStatus()).isEqualTo(InformationRequestStatus.SUBMITTED);verify(events).publishEvent(any(InformationSubmittedEvent.class));}
}
