package com.chubb.apac.claims.modulith.claim.controller;
import com.chubb.apac.claims.modulith.claim.dto.response.*;import com.chubb.apac.claims.modulith.claim.service.ClaimService;import com.chubb.apac.claims.modulith.common.dto.*;import com.chubb.apac.claims.modulith.common.enums.*;import com.chubb.apac.claims.modulith.common.security.CurrentUser;import com.chubb.apac.claims.modulith.common.util.CorrelationId;import org.springframework.data.domain.PageRequest;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/staff/claims") @PreAuthorize("hasAnyRole('CLAIMS_STAFF','MANAGER')")
public class StaffClaimController {private final ClaimService service;public StaffClaimController(ClaimService service){this.service=service;}
 @GetMapping public PageResponse<ClaimResponse> list(@AuthenticationPrincipal CurrentUser user,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size,@RequestParam(required=false) ClaimStatus status,@RequestParam(required=false) Market market,@RequestParam(required=false) ProductType productType,@RequestParam(required=false) String assignedTo){return service.listForStaff(user.markets(),status,market,productType,assignedTo,PageRequest.of(page,size));}
 @GetMapping("/{claimId}") public ApiResponse<ClaimDetailResponse> get(@AuthenticationPrincipal CurrentUser user,@PathVariable String claimId){return ApiResponse.success(service.getForStaff(user.markets(),claimId));}
 @PostMapping("/{claimId}/assign") @PreAuthorize("hasRole('CLAIMS_STAFF')") public ApiResponse<ClaimAssignmentResponse> assign(@AuthenticationPrincipal CurrentUser user,@PathVariable String claimId,@RequestHeader(value=CorrelationId.HEADER,required=false) String correlationId){return ApiResponse.success(service.assignToSelf(user.markets(),user.userId(),claimId,correlationId));}
 @PostMapping("/{claimId}/unassign") @PreAuthorize("hasRole('CLAIMS_STAFF')") public ApiResponse<ClaimUnassignmentResponse> unassign(@AuthenticationPrincipal CurrentUser user,@PathVariable String claimId,@RequestHeader(value=CorrelationId.HEADER,required=false) String correlationId){return ApiResponse.success(service.unassignFromSelf(user.markets(),user.userId(),claimId,correlationId));}
}
