package com.chubb.apac.claims.modulith.claim.api;
import com.chubb.apac.claims.modulith.claim.event.ClaimStatusChangedEvent;import com.chubb.apac.claims.modulith.claim.model.*;import com.chubb.apac.claims.modulith.claim.repository.*;import com.chubb.apac.claims.modulith.common.enums.*;import com.chubb.apac.claims.modulith.common.exception.*;import java.time.Instant;import java.util.*;import org.springframework.context.ApplicationEventPublisher;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional
public class ClaimWorkflowApiImpl implements ClaimWorkflowApi {
 private final ClaimRepository claims;private final ClaimStatusHistoryRepository history;private final ApplicationEventPublisher events;
 public ClaimWorkflowApiImpl(ClaimRepository claims,ClaimStatusHistoryRepository history,ApplicationEventPublisher events){this.claims=claims;this.history=history;this.events=events;}
 @Transactional(readOnly=true) public ClaimAccessView requireAssignedStaffClaim(String id,String staff,Set<Market> markets){Claim c=find(id,markets);if(c.getAssignedStaffId()==null||!c.getAssignedStaffId().equals(staff))throw new ForbiddenException("Claim is not assigned to current staff member");return view(c);}
 @Transactional(readOnly=true) public ClaimAccessView requireManagerClaim(String id,Set<Market> markets){return view(find(id,markets));}
 public ClaimAccessView transition(String id,Set<Market> markets,ClaimStatus expected,ClaimStatus next,String reason,String actor,String correlationId){Claim c=claims.findForUpdate(id,markets).orElseThrow(()->new ResourceNotFoundException("Claim not found"));if(c.getStatus()!=expected)throw new ConflictException("Claim is not in the required state: "+expected);ClaimStatus old=c.getStatus();c.setStatus(next);c.setUpdatedBy(actor);ClaimStatusHistory h=new ClaimStatusHistory();h.setClaimId(id);h.setOldStatus(old);h.setNewStatus(next);h.setReason(reason);h.setChangedBy(actor);h.setChangedAt(Instant.now());h.setCreatedBy(actor);h.setUpdatedBy(actor);history.save(h);events.publishEvent(new ClaimStatusChangedEvent(UUID.randomUUID().toString(),id,old,next,reason,actor,Instant.now(),correlation(correlationId)));return view(c);}
 private Claim find(String id,Set<Market> markets){if(markets==null||markets.isEmpty())throw new ForbiddenException("No market access is assigned");return claims.findByClaimIdAndMarketIn(id,markets).orElseThrow(()->new ResourceNotFoundException("Claim not found"));}
 private ClaimAccessView view(Claim c){return new ClaimAccessView(c.getClaimId(),c.getClaimantId(),c.getStatus(),c.getMarket(),c.getProductType(),c.getAssignedStaffId());}private String correlation(String v){return v==null||v.isBlank()?UUID.randomUUID().toString():v;}
}
